version: "3.9"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - dev-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis
    ports:
      - 6379:6379
volumes:
  dev-db:
